import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About NavBar</nav>
      <main className=" min-h-screen grid place-content-center bg-gray-900 gap-5">
        {children}
      </main>
    </>
  );
}
